### ISSUE TITLE
Error for an unexpected token while on code coverage

### ISSUE THREAD

**Issue by Randairox** [sindresorhus/find-up#34]
When I try to execute a code coverage operation in CircleCI, the following error pops up: 
```
/home/circleci/repo/node_modules/nyc/node_modules/find-up/index.js:5
module.exports = (filename, opts = {}) => {
                                 ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/circleci/repo/node_modules/nyc/lib/config-util.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! Test failed.  See above for more details.
Exited with code 1
```

**Comment by Randairox** [comment]
This seemed to hit the right spot! Thank you very much.

Though I'm still surprised, because when using:
```yaml
      - run:
          name: update_apt
          command: curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
      - run:
          name: update_node
          command: sudo apt-get install -y nodejs
```
to "update" the environment, it really doesn't _truly_ do so, if the error was still being thrown
